apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cdm-service
  name: cdm-service
spec:
  ports:
    - name: "5013"
      port: 5013
      targetPort: 5000
  selector:
    io.kompose.service: cdm-service
status:
  loadBalancer: {}
