apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dds-service
  name: dds-service
spec:
  ports:
    - name: "5012"
      port: 5012
      targetPort: 5000
  selector:
    io.kompose.service: dds-service
status:
  loadBalancer: {}
